trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
# Configurar Java 17
- task: JavaToolInstaller@0
  inputs:
    versionSpec: '17'
    jdkArchitecture: 'x64'
    jdkSourceOption: 'PreInstalled'

# Compilar el proyecto con Maven sin ejecutar tests
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean package -DskipTests'
